# https://docs.gitlab.com/12.10/ee/api/jobs.html
image: node:latest

services:
  - docker:19.03.1-dind
before_script:
  - docker pull stackhawk/hawkscan
hawkscan:
  script:
    - |
      docker run -v $(pwd):/hawk:rw -t \
        -e API_KEY="hawk.${HAWK_API_ID}.${HAWK_API_SECRET}" \
        -e NO_COLOR=true \
        stackhawk/hawkscan

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - yarn
  script:
    - cd front-end && yarn test
    - cd ../

build:
  stage: build
  before_script:
    - export PATH=$PATH:/root/.nvm/versions/node/v14.18.3/bin
    - echo "PATH='${PATH}'"
    # - rm -rf node_modules
    - yarn
  script:
    - cd front-end && yarn install
    - cd ../
    - yarn front-end:build
    - rm -rf output
    - mkdir output
    - mkdir output/back-end
    - mkdir output/front-end
    - cp -r front-end/build/ output/front-end/
    - cp -r back-end/ output/back-end/
  artifacts:
    paths:
      - output/**/*
    expire_in: 4h
  only:
    - ui

deploy:
  stage: deploy
  #  when: manual
  before_script:
    - export PATH=$PATH:/root/.nvm/versions/node/v14.18.3/bin
    # - /root/.nvm/versions/node/v14.18.3/bin/pm2 --version
    - echo "PATH='${PATH}'"
    - rm -rf front-end/build/
    - npm config set cache .npm
    - yarn
  script:
    - cp -r output/front-end/ front-end
    - cp -r output/back-end back-end
    # - /root/.nvm/versions/node/v14.18.3/bin/pm2 start
  only:
    - ui
