version: '3'
services:
  back-end:
    container_name: pet-website-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '8808:8808'
    volumes:
      - ./back-end:/app
      - /app/node_modules
    command: yarn start
    networks:
      - common

  front-end:
    stdin_open: true
    tty: true
    container_name: pet-website-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - '3002:3002'
    volumes:
      - ./front-end:/app
      - /app/node_modules
    networks:
      - common

networks:
  common:
